root: true
env:
  browser: true
  es2021: true
  jest: true
extends:
  - airbnb-base
  - plugin:prettier/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  curly:
    - error
    - all
  no-console: off
  import/extensions: off
  import/no-dynamic-require: off
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
        - heights
