root: true
env:
  browser: true
  es2021: true
  jest: true
extends:
  - airbnb-base
  - plugin:prettier/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: off
  import/extensions: off
  import/no-dynamic-require: off
